### ISSUE TITLE
Duplicated Champions On Profile

### ISSUE THREAD

**Issue by cookieman768** [molenzwiebel/OriannaBot#10]
Morgana is appearing twice and their number of mastery 7 champions is doubled. We’ve tried refreshing their profile but the problem persists. 

![Image of Issue](https://i.imgur.com/qgEKN2z.jpg)

**Comment by molenzwiebel** [comment]
I haven't fully figured out why this is happening (it seems to be very rare), but I've fixed it for this particular user. Thanks for the report, I'll keep an eye out if other people have duplicated entries.

**Comment by cookieman768** [comment]
Ahh. I figured it must be rare since I’ve never encountered it before. Great job on your bot!
