### ISSUE TITLE
Feature request: and/or for conditions

### ISSUE THREAD

**Issue by heroesofthesean** [molenzwiebel/OriannaBot#12]
I'm in love with the new condition system to make roles, however could you make it so that it can look at either a combination of conditions or only one of them being there? For instance I want to make a support role, looking at a high mastery score or level for (for instance) 3 supports, instead of all supports. 

I guess that's somewhat of a vague description. I guess an option to select something like "player must score positive for all/one/any # of conditions"

Obligatory NotAProgrammer so I'm not sure if this would be impossible to make. If it is impossible, disregard this!

**Comment by molenzwiebel** [comment]
I believe this is what you were looking for? If yes, it was just deployed as 15e3b75!
![2018-11-05_18-36-21](https://user-images.githubusercontent.com/3594254/48017207-faa9a580-e12d-11e8-89fd-e747d1d144ac.gif)

**Comment by heroesofthesean** [comment]
Yes, awesome!
