### ISSUE TITLE
Deleted account

### ISSUE THREAD

**Issue by Wixonater1** [molenzwiebel/OriannaBot#13]
I deleted a discord account with my league account attached, so now I can't connect my league account to my new discord account. I tried using the discord profile it tells you to add for issues and that aslso didn't work.

**Comment by molenzwiebel** [comment]
Hey sorry, I read this but forgot to respond. Please contact me by adding `molenzwiebel#2773` as a friend on Discord. If that doesn't work, try joining https://discord.gg/bfxdsRC
