### ISSUE TITLE
Error code when requesting server roles

### ISSUE THREAD

**Issue by heroesofthesean** [molenzwiebel/OriannaBot#14]
Hi there, after the new update I went wild with roles and added a whole bunch of them, a lot of them with a whole list of conditions where (usually) 5 were required to match. However this has caused the command to request server roles to be unavailable, with the following error code: 1b5d13a7b7f1ede93575445fea5678de

I can list the roles and conditions if that would help?

**Comment by molenzwiebel** [comment]
Looks like Discord was simply complaining that I was sending too much text in a single field. I changed up the code in e5bcd12f to split the conditions over multiple fields if it becomes too large (see image). This should fix your problems. If not, please reopen the issue.
![image](https://user-images.githubusercontent.com/3594254/48973539-abc2a200-f041-11e8-9be2-22e4f69d468e.png)

**Comment by heroesofthesean** [comment]
Works indeed, you're amazing!
