### ISSUE TITLE
After Transfer Problems

### ISSUE THREAD

**Issue by RakanBoi** [molenzwiebel/OriannaBot#16]
Hello! I have issues assigning my account to Ori after transfering to another region. 

I unbind my account because even tho i kept refreshing, Ori still showed my old name and server. The configuration link doesn't work, the LoL client won't accept it. Importing from Discord isn't working either.

**Comment by molenzwiebel** [comment]
Sounds like the Riot verification service is broken once again. Please add me on Discord, molenzwiebel#2773, and I'll manually add the account for you. Unfortunately the verification issue is out of my control :(
