### ISSUE TITLE
Feature Request: Apply Summoner name as Discord nickname

### ISSUE THREAD

**Issue by Trikolon** [molenzwiebel/OriannaBot#20]
Upon linking their account the bot could set the users Discord nickname to their LoL summoner name.

If the user has linked multiple accounts you could provide the option to set a default / main one.

The nickname feature could be toggled on / off per server by admins.

**Comment by molenzwiebel** [comment]
This has been implemented as nickname pattern. Using `{username}` as pattern will achieve what you want.
