### ISSUE TITLE
Unable to  configure Orianna bot

### ISSUE THREAD

**Issue by ZachariBarnes** [molenzwiebel/OriannaBot#35]
I've been trying for quite awhile to configure Orianna bot on a server I joined but this is all I get when I try.
![Capture](https://user-images.githubusercontent.com/10678967/88458095-09c80e00-ce51-11ea-932f-0bfc1453cbb5.PNG)

**Comment by ZachariBarnes** [comment]
I've tried @oriannabot in the chat as well but its the same result, she just sends me a blank message

**Comment by molenzwiebel** [comment]
Go into your Discord settings, Text & Appearance, and turn the "Show website preview info" setting on.
