### ISSUE TITLE
Server configuration link not received

### ISSUE THREAD

**Issue by Apostolique** [molenzwiebel/OriannaBot#4]
After adding the Orianna Bot to my server, I didn't receive any PM to configure the server.

If I try a command like "server edit", I get a check mark, then:

```Slow Down! The owner of this server hasn't yet finished configuring me. Come back later!```

What do I do now? I'm the server owner.

**Comment by molenzwiebel** [comment]
Alright, so a couple of things could be happening here. Let’s start with the obvious ones.

- Are you actually the server owner? Are you able to delete the server? The owner has a little crown in the members list in the server settings.

- Do you have direct messages disabled? Ori might have attempted to send you a message but failed.

If it’s not one of these, feel free to add me on Discord (`molenzwiebel#2773`) and I’ll walk you through the setup manually.

**Comment by Apostolique** [comment]
I added you.

Indeed I have the crown icon. My messages are also not disabled. Orianna Bot was able to send me my profile configuration link. It's just the server configuration link that isn't sent.

**Comment by Apostolique** [comment]
Problem is fixed, the Orianna Bot had not added the server to it's database. Kicking it and reinvited the bot fixed it.
