### ISSUE TITLE
[Enhancement / Feature Request] Leauge accounts should be verified using third party verification

### ISSUE THREAD

**Issue by jeliebig** [molenzwiebel/OriannaBot#47]
Hello,

I just added my League account to the bot and noticed that it asked for a summoner icon change, instead of giving me a third party verification code. Since those codes are specifically made for third party verification, I think it would be awesome to use them to verify account ownership over the current method with changing icons.

Showing a screenshot of the verification tab, so you can see how easy it would be to verify account ownership with it.
![image](https://user-images.githubusercontent.com/20988865/108493046-2cff5280-72a6-11eb-99e0-cc5dd6a63735.png)

**Comment by molenzwiebel** [comment]
Orianna used to use this feature but it was (and still is) notoriously unreliable. There have been multiple spans where the feature was unavailable for **weeks** at a time.

The summoner icon change is certainly a hack but at least I can be sure that it works 100% of the time.
