### ISSUE TITLE
Feature request: Opt-out of region role

### ISSUE THREAD

**Issue by Apostolique** [molenzwiebel/OriannaBot#5]
On my server, we can @message regions like @na. Unfortunately Discord doesn't allow people to mute role pings which can be annoying for some people.

Right now there's already an option to 'Opt-Out of Tier Roles' on the web interface. We should also have an option to 'Opt-Out of Region Roles'.

**Comment by molenzwiebel** [comment]
Would you still be interested in this now that role conditions have been reworked?
