### ISSUE TITLE
Is there a way to get the league ids and region of all the members of my server from Orianna?

### ISSUE THREAD

**Issue by kintama48** [molenzwiebel/OriannaBot#51]
I am making a new bot for my server and I would like it if I can get the required information from Orianna directly, instead of asking the members again. I have to work with the LoL API.

**Comment by molenzwiebel** [comment]
Please contact me on Discord, `@molenzwiebel#2773`, to discuss details. It _might_ be possible, but I have to consider privacy of the users so I cannot make any guarantees.
