### ISSUE TITLE
Orianna bot isn't keeping up to date for all my champions

### ISSUE THREAD

**Issue by LillieShi** [molenzwiebel/OriannaBot#52]
when i type top server Orianna it shows someone with 39K points at the top and says i am rank >10,000 but i currently have 46K points, i'm not sure why it isn't keeping up to date

**Comment by LillieShi** [comment]
In addition to this it also places my tft rank as bronze when i am currently gold 4

**Comment by kumsaltoprak** [comment]
> En iyi sunucu Orianna yazdığımda, en üstte 39K puana sahip birini gösteriyor ve 10.000 > olduğumu söylüyor, ancak şu anda 46K puanım var, neden güncel olmadığından emin değilim

Hangi sunucudan bağlanıyorsunuz acaba ?
