### ISSUE TITLE
Can't Log Out Of The /me Page

### ISSUE THREAD

**Issue by karimawii** [molenzwiebel/OriannaBot#53]
I use 2 different discord account with the new account switcher in control, and https://orianna.molenzwiebel.xyz/me only detects one of them and doesn't let me switch between them or even log out, the only solution I found was to get the Auth link by typing `@orianna bot edit` and use it to access the desired account page

**Comment by molenzwiebel** [comment]
Yes, I should probably add a sign-out button.
