### ISSUE TITLE
feature request: add in Garena servers

### ISSUE THREAD

**Issue by FateGasm** [molenzwiebel/OriannaBot#6]
Since op.gg supports Garena servers now i guess it'll be available...?

**Comment by molenzwiebel** [comment]
The Riot Games API for Garena regions is currently in closed beta. Once I either get into the beta or once it becomes public, I'll add the regions to Orianna. In the meantime, nothing I can do 😦

**Comment by molenzwiebel** [comment]
The Garena API has unfortunately been [sunsetted](https://www.riotgames.com/en/DevRel/sunsetting-the-riot-games-api-garena-beta), so there's no way for me to support Garena in the near future. :(

**Comment by MingweiSamuel** [comment]
Should be coming soon™

**Comment by molenzwiebel** [comment]
Ex-Garena regions are supported now.
