### ISSUE TITLE
Orianna Bot doesn't respect Discord nicknames

### ISSUE THREAD

**Issue by Apostolique** [molenzwiebel/OriannaBot#7]
In Discord, if the option is enabled, it's possible for people to change their nickname. Orianna Bot should use that nickname within the server.

For example:

![image](https://user-images.githubusercontent.com/2766423/40645168-8ac1c224-62f3-11e8-9dae-346b2cd40b31.png)

**Comment by molenzwiebel** [comment]
This should be fixed in Orianna v2, which went live last week. Let me know if it still applies.
